language: node_js
node_js:
  - "10"
  - "12"
  - "13"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm run lint
  - npm run init-db
  - npm test
