language: node_js
node_js:
  - "10"
  - "12"
  - "13"
services: mongodb  
cache:  
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm install
  - docker-compose run --rm web npm run init-db
  - docker-compose up
